### ISSUE TITLE
Graphics!

### ISSUE THREAD

**Issue by schibel21** [Lexden12/TicketToRideGame#17]
I was very confused about why the background on the right of the screen turns red after you switch to player one's turn and then stays that color during your turn (Player Zero). Also the text view is difficult to see who's turn it is at the top.

**Comment by Lexden12** [comment]
Thank you for bringing this to my attention! The flasher has been patched to return to the black background after 100 millis. As for the text view for the turn, do you have any suggestions on a better color? Thanks.

**Comment by Cameron94857** [comment]
Thank you for your valuable feedback! The issue has been resolved.
