### ISSUE TITLE
Suggestion for AI Playing Route

### ISSUE THREAD

**Issue by liao21** [Lexden12/TicketToRideGame#25]
If displaying trains on the board is too hard, a textbox with the AI's most recent move would be helpful. This may even be useful for debugging.

**Comment by Lexden12** [comment]
We do hope to display on the board soon, but currently the AI is only set to draw train cards.

**Comment by Lexden12** [comment]
We do hope to display on the board soon, but currently the AI is only set to draw train cards.

**Comment by Cameron94857** [comment]
Thank you for your valuable feedback! Your suggestion has been taken into consideration.
