### ISSUE TITLE
Game Crashes Upon Emptying Draw Pile

### ISSUE THREAD

**Issue by Katacka** [Lexden12/TicketToRideGame#26]
As described by the title, the game crashes if the draw pile is emptied of all its cards. I'm guessing that this occurs due to the deck not being reshuffled, resulting in draw being called on a null object reference

**Comment by Lexden12** [comment]
Did you ever claim any routes? If there are cards in the discard pile, then it should reshuffle.

**Comment by Lexden12** [comment]
Thanks for letting us know about this bug! It was just patched.
